### PR TITLE
Added OER Support, restored from ancient java-crypto-condition version

### PR DESCRIPTION
**Pull request by earizon**
Restored (org.interledger.encoding.)OerInputStream and OerOutputStream

### CODE REVIEW

**Comment by earizon** [comment]
@sappenin 
> Any chance we could get unit tests for these? There is a new ILP binary packet being defined that might be a good candidate, but perhaps a more general set of tests is in order?

I just added a "draft" unit-test that writes OER to memory, then reads it backs. Far away from perfect, but still useful as documentation. Definetly testing with real ILP packet data is a "must".

https://github.com/interledger/java-ilp-core/pull/20/files#diff-287749664ce9c22151c7148d5b068c79

**Comment by sappenin** [comment]
LGTM!  Can you merge this, or do I need to?

**Comment by adrianhopebailie** [comment]
@earizon, you should be able to merge. Let me know if not.

**Comment by adrianhopebailie** [comment]
@earizon the flow we are adopting is for committers to merge their own PRs once they have been reviewed and approved.

I've merged this one so it doesn't go stale

**Comment by earizon** [comment]
@adrianhopebailie  (overflowed by a jungle of emails). Got it for next time!

**Pull request merged**
