### PR TITLE
feat: implement PSK message (RFC 16)

### PR DESCRIPTION
**Pull request by andrew-g-za**
First stab at a PSK message implementation.

I'm not convinced the design is correct - opinions gratefully accepted.
It also seems to rely heavily on byte[] - not sure if its worth moving to nio and ByteBuffer?

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
> Seems we might want to hold this PR until IL-RFC #197 is resolved (Should public headers be removed from PSK)?

Since we have no PSK functionality at all I'd suggest we merge and then adjust when [IL-RFC #197](https://github.com/interledger/rfcs/issues/197) is resolved.

**Comment by sappenin** [comment]
Sounds good to me -- looks like a few test failures, but once that passes I'm good if this gets merged.

**Comment by andrew-g-za** [comment]
Cool, thanks for the feedback.
My bad, I didn't spot the test-case failure the first time :(
I'm pretty sure its related to the 256-bit key length, which requires the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files. I'll try figure out how to get that into CircleCI

**Comment by andrew-g-za** [comment]
JCE policy now deploying in circleci, looks like the tests are passing. I see the previous commit for the OER encoding upset checkstyle, will fix in another submission.

**Comment by sappenin** [comment]
One other thought I had - what if we bump the version to 0.3.0-SNAPSHOT for this commit?

**Comment by andrew-g-za** [comment]
Yup, great idea. Let me get the OER fixes in underneath first, then we can use the PSK change to bump the release to v0.3 as you suggest (I wouldn't want to push this release as v0.3 then immediately have to commit small style changes into it).

**Comment by sappenin** [comment]
+1.  Looks like #27 is good to go.

**Pull request merged**
